name: 'Setup vcpkg'
description: 'Install Microsoft`s vcpkg management tool'
author: 'Jonatan Antoni <jonatan.antoni@arm.com>'

inputs:
  version:
    description: The version of vcpkg to install.
    default: "2026.06.01"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Clone vcpkg
      uses: actions/checkout@v6
      with:
        repository: microsoft/vcpkg
        path: .vcpkg
        ref: ${{ inputs.version }}

    - name: Bootstrap vcpkg [Windows]
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        ${{ github.workspace }}/.vcpkg/bootstrap-vcpkg.bat
        echo ${{ github.workspace }}/.vcpkg/ >> $GITHUB_PATH

    - name: Check vcpkg installation [Windows]
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        where vcpkg
        vcpkg version

    - name: Bootstrap vcpkg [Linux/Mac]
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ${{ github.workspace }}/.vcpkg/bootstrap-vcpkg.sh
        echo ${{ github.workspace }}/.vcpkg/ >> $GITHUB_PATH

    - name: Check vcpkg installation [Linux/Mac]
      if: runner.os != 'Windows'
      shell: bash
      run: |
        which vcpkg
        vcpkg version
