on: 
  pull_request: 
    branches: main
    paths:
      - vcpkg/*
      - .github/workflows/vcpkg-action.yml
  push:
    branches: main
    paths:
      - vcpkg/*
      - .github/workflows/vcpkg-action.yml
  workflow_dispatch:

jobs:
  test:
    name: Test vcpkg action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022, ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, macos-13, macos-14]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup vcpkg
        uses: ./setup-vcpkg

      - name: Activate vcpkg environment
        uses: ./vcpkg
        with:
          config: ./vcpkg/vcpkg-configuration.json
          cache: -${{ matrix.os }}

      - name: Verify some tools
        run: |
          which cpackget
          which cbuild
